#!/usr/bin/env bash

# Dotfiles Bootstrap Installer
# Installs Git, Zsh, Homebrew, and Dotfiles

set -e

e='\033'
RESET="${e}[0m"
CYAN="${e}[0;96m"
GREEN="${e}[0;92m"
RED="${e}[0;91m"
YELLOW="${e}[0;93m"

_exists() {
  command -v "$1" > /dev/null 2>&1
}

info() { echo -e "${CYAN}${*}${RESET}"; }
success() { echo -e "${GREEN}${*}${RESET}"; }
error() { echo -e "${RED}${*}${RESET}"; }
finish() { success "Done!\n"; sleep 1; }

export DOTFILES=${1:-"$HOME/.dotfiles"}
GITHUB_REPO_URL_BASE="https://github.com/denysdovhan/dotfiles"

trap on_error SIGTERM

on_error() {
  echo
  error "Oops! Something went wrong."
  error "Last error message: $(tail -n 1 /tmp/bootstrap-error.log)"
  error "For debugging, check: ${CYAN}${GITHUB_REPO_URL_BASE}/issues/new${RESET}"
  echo
  exit 1
}
exec 2>/tmp/bootstrap-error.log  # Capture errors

install_homebrew() {
  info "Checking Homebrew..."

  if ! _exists brew; then
    info "Installing Homebrew..."
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    success "Homebrew is already installed!"
  fi
  finish
}

install_git() {
  info "Checking for Git..."
  if _exists git; then success "Git is already installed!"; return; fi
  info "Installing Git..."
  [ "$(uname)" = "Darwin" ] && brew install git || sudo apt update && sudo apt install -y git
  finish
}

install_zsh() {
  info "Checking for Zsh..."
  if _exists zsh; then success "Zsh is already installed!"; return; fi
  info "Installing Zsh..."
  [ "$(uname)" = "Darwin" ] && brew install zsh || sudo apt install -y zsh
  finish
}

install_software() {
  [ "$(uname)" != "Darwin" ] && return
  info "Updating Homebrew..."
  brew update
  info "Installing software..."
  brew bundle
  finish
}

install_npm() {
  [ "$(uname)" != "Darwin" ] && return
  if ! _exists npm; then error "npm is missing!"; return; fi
  info "Installing global npm packages..."
  npm install -g commitizen npkill fkill-cli cz-conventional-changelog
  finish
}

main() {
  install_homebrew
  install_git
  install_zsh
  install_software
  install_npm
  success "Setup complete! Restart terminal for changes to apply."
}

main
